name: chess_sharp_dart
description: Forked from dartchess (by lichess) version 0.11.1 on 2025-12-09 to include the Chessâ™¯ family of variants
repository: https://github.com/dbergan/chess_sharp_dart
version: 0.1.4
homepage: https://chess-sharp.games/
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  fast_immutable_collections: ^11.0.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: ^1.3.0
  meta: ^1.8.0
  web: ^1.0.0

dev_dependencies:
  benchmark: ^0.3.0
  js: ^0.7.0
  lint: ^2.6.1
  test: ^1.25.0
